name: pick_country_picker
description: A highly customizable Flutter package for selecting a country from a modal list.
version: 0.0.5
homepage: https://github.com/ThickLine/pick_country_picker

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/flags/

  # This adds support for localization and internationalization.
  uses-material-design: true
  generate: true


