name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write  # Permission for pub.dev authentication
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v2  # Sets up a Dart environment
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test

      - name: Analyze code
        run: dart analyze

      - name: Check for publish warnings
        run: dart pub publish --dry-run

      - name: Publish to pub.dev
        run: dart pub publish
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}